### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by mrocklin** [blaze/castra#61]
Any thoughts on adding a deprecation message or generally a louder warning in the README?

**Comment by jcrist** [comment]
A louder warning in the README sounds good to me. Perhaps just bump the current one to the top, and change the description to something like `partitioned storage system based on blosc [UNMAINTAINED]`?

**Comment by thequackdaddy** [comment]
Hello,

Forgot that awhile back, I made #60 .

It looks like this project is being deprecated. Too bad. I thought you were doing amazing work. (I'm not volunteering to take this over... I'm nowhere near competent for that.) 

Can I ask if that's just because of a lack of interest or you are going to focus development on things like bcolz (or another project with overlap) instead? I'm trying to find the best on-disk data column-chunked compressed datastore for my purpose. They all have pluses and minuses. 

Thanks for at least demo-ing this. I had fun toying with it.

**Comment by mrocklin** [comment]
It's still around.  I just don't personally intend to actively maintain it.  This isn't due to any particular flaw with the project, I just don't have enough time and there is no clear replacement who does have enough time.
